- name: variables
  web: localhost
  vars: #variable declarartion
    Course: "Terraform"
    Trainer: "Siva"
    Duration: "15hrs"
  tasks:
  - name: print information
    vars: # Task level variables
      Course: "DevOps"
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Durartion is {{Duration}}."
    